### PR TITLE
Support for Synthetics-RunId

### PR DESCRIPTION
**Pull request by jtmalinowski**
# Description

Splunk Synthetic Monitoring want to use a dedicated baggage field to mark traces as synthetic. Propagate this field using baggage, and set as an attribute on appropriate spans.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Tested manually
- [x] Added automated tests

# Checklist:

- [x] Changelogs have been updated
- [x] Unit tests have been added/updated
- [x] Documentation has been updated

### CODE REVIEW

**Review by Rauno56 — COMMENTED** [review]
Looks good!
Since I'm not familiar with the concept: It basically adds a Splunk-standard `Synthetics-RunId` field to baggage to be propagated around. Based on that field the backend can then filter out test runs. Accurate?
Is there any docs/material on this?

**Review by Rauno56 — APPROVED** [review]

**Comment by jtmalinowski** [comment]
The decision to use `baggage` is to be rereviewed.

**Comment by Rauno56** [comment]
> The decision to use `baggage` is to be rereviewed.

What's the alternative?

**Comment by jtmalinowski** [comment]
@Rauno56 [Tracestate](https://www.w3.org/TR/trace-context/#tracestate-header) for one. But we cleared the `baggage` for use here.

**Pull request merged**
